class SelectMenuLocators:
    MAIN_CONTAINER = "#app"
    CONTAINER = "#withOptGroup"
    SELECT_VALUE = "#oldSelectMenu"
    MULTISELECT = "#cars"
    SELECT_ONE_CONTAINER = "#selectOne"
    SELECT_ONE_DISPLAY_TEXT = ".css-1hwfws3"
    DROPDOWN_MENU = ".css-26l3qy-menu"
    DROPDOWN_OPTIONS = ".css-yt9ioa-option"
    DROPDOWN_CONTROL = ".css-yk16xz-control"
    DROPDOWN_VALUE = "div.css-1hwfws3"
    MULTISELECT_CONTROL = "div.css-yk16xz-control"
    SELECTED_TAG = ".css-1rhbuit-multiValue"
    SELECTED_TAG_TEXT = ".css-12jo7m5"
    CLOSEBUTTON = "div.css-xb97g8"
    PLACEHOLDER = "div.css-1wa3eu0-placeholder"
